---
cache: pip
language: python

python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

install:
- pip install .[all]

script:
- pytest